version: 2
updates:

  - package-ecosystem: "github-actions"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "weekly"
