version: "3"

services:
  tsr:
    image: ghcr.io/mkody/twitch-stream-recorder:master
    # You can also change the UID/GID and the username
    # used in the container and build the image again
    # with `--build` when launching your compose stack.
    build:
      context: .
      args:
        UNAME: user
        UID: 1000
        GID: 1000
    environment:
      - USERNAME=your_favourite_streamer
      - CLIENT_ID=your_client_id
      - CLIENT_SECRET=your_client_secret
      # - AUTH_TOKEN=your_oauth_token_cookie
    volumes:
      - /path/to/recordings:/opt/recordings
    restart: unless-stopped

  # If you want to run it for multiple streamers:
  # - duplicate the whole "tsr" section
  # - change the "twitch-stream-recorder" service name to something else
  #   (ie. `tsr-bobross`) as they have to be unique
  # - and set the new username in the `USERNAME` env
