version: "3"

services:
  tsr:
    image: ghcr.io/mkody/twitch-stream-recorder:master
    # You can also change the UID/GID and the username
    # used in the container and build the image again with 
    # `docker compose build` or `docker compose up -d --build`.
    build:
      context: .
      args:
        UNAME: user
        UID: 1000
        GID: 1000
    environment:
      - USERNAME=your_favourite_streamer
      - QUALITY=best
      - CLIENT_ID=your_client_id
      - CLIENT_SECRET=your_client_secret
      # - AUTH_TOKEN=your_oauth_token_cookie
    volumes:
      - /path/to/recordings:/opt/recordings
    restart: unless-stopped

  # I'd recommend to remove the "=" and values after CLIENT_ID, CLIENT_SECRET
  # and AUTH_TOKEN and set them in a `.env` file instead.

  # If you want to run it for multiple streams:
  # - duplicate the whole "tsr" section
  # - change the "tsr" service name to something else
  #   (ie. `tsr-bobross`) since they have to be unique
  # - set the new username in the `USERNAME` env
